# Generated by Django 4.2.6 on 2023-12-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_course_name_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='exit', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('cm', 'Chemistry'), ('bio', 'Biology')], default='exit', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='purpose',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('place_order', 'Place Order'), ('return', 'Return')], max_length=50),
        ),
    ]
